/**
 * TrustLens Initial Trusted Computer Science Knowledge Seed Dataset
 * Contains 65 atomic, factual Computer Science knowledge entries across 5 core topics.
 * Authoritative sources: NIST, IEEE, ACM, W3C, ISO/IEC, RFC Editor, Oracle Docs, Linux Kernel Docs, MIT OCW.
 */

const TRUSTED_KNOWLEDGE_SEED = [
  // =========================================================================
  // 1. CLOUD COMPUTING (13 Entries)
  // =========================================================================
  {
    seedId: 'cs-cloud-001',
    title: 'NIST Cloud Computing Definition',
    domain: 'Computer Science',
    topics: ['Cloud Computing'],
    sourceType: 'Official Documentation',
    sourceOrganization: 'NIST',
    sourceUrl: 'https://csrc.nist.gov/publications/detail/sp/800-145/final',
    description: 'NIST Special Publication 800-145 formal definition of cloud computing.',
    text: 'Cloud computing is a model for enabling ubiquitous, convenient, on-demand network access to a shared pool of configurable computing resources (networks, servers, storage, applications, and services) that can be rapidly provisioned and released with minimal management effort or service provider interaction.',
    status: 'active',
  },
  {
    seedId: 'cs-cloud-002',
    title: 'On-Demand Self-Service Characteristic',
    domain: 'Computer Science',
    topics: ['Cloud Computing'],
    sourceType: 'Official Documentation',
    sourceOrganization: 'NIST',
    sourceUrl: 'https://csrc.nist.gov/publications/detail/sp/800-145/final',
    description: 'Essential cloud computing characteristic of self-service provisioning.',
    text: 'On-demand self-service allows a consumer to unilaterally provision computing capabilities, such as server time and network storage, as needed automatically without requiring human interaction with each service provider.',
    status: 'active',
  },
  {
    seedId: 'cs-cloud-003',
    title: 'Broad Network Access Characteristic',
    domain: 'Computer Science',
    topics: ['Cloud Computing'],
    sourceType: 'Official Documentation',
    sourceOrganization: 'NIST',
    sourceUrl: 'https://csrc.nist.gov/publications/detail/sp/800-145/final',
    description: 'Essential cloud computing characteristic of network accessibility.',
    text: 'Broad network access mandates that cloud capabilities are available over the network and accessed through standard mechanisms that promote use by heterogeneous thin or thick client platforms (e.g., mobile phones, tablets, laptops, and workstations).',
    status: 'active',
  },
  {
    seedId: 'cs-cloud-004',
    title: 'Resource Pooling and Multi-Tenancy',
    domain: 'Computer Science',
    topics: ['Cloud Computing'],
    sourceType: 'Official Documentation',
    sourceOrganization: 'NIST',
    sourceUrl: 'https://csrc.nist.gov/publications/detail/sp/800-145/final',
    description: 'Multi-tenant infrastructure pooling model in cloud computing.',
    text: 'Resource pooling involves serving multiple consumers using a multi-tenant model, with different physical and virtual resources dynamically assigned and reassigned according to consumer demand, creating location independence for computing assets.',
    status: 'active',
  },
  {
    seedId: 'cs-cloud-005',
    title: 'Rapid Elasticity',
    domain: 'Computer Science',
    topics: ['Cloud Computing'],
    sourceType: 'Official Documentation',
    sourceOrganization: 'NIST',
    sourceUrl: 'https://csrc.nist.gov/publications/detail/sp/800-145/final',
    description: 'Dynamic scaling capability of cloud infrastructure.',
    text: 'Rapid elasticity enables computing capabilities to be elastically provisioned and released, in some cases automatically, to scale rapidly outward and inward commensurate with demand so resources appear infinite to the consumer.',
    status: 'active',
  },
  {
    seedId: 'cs-cloud-006',
    title: 'Measured Service Model',
    domain: 'Computer Science',
    topics: ['Cloud Computing'],
    sourceType: 'Official Documentation',
    sourceOrganization: 'NIST',
    sourceUrl: 'https://csrc.nist.gov/publications/detail/sp/800-145/final',
    description: 'Metered resource usage monitoring in cloud environments.',
    text: 'Cloud systems automatically control and optimize resource use by leveraging a metering capability at some level of abstraction appropriate to the type of service (e.g., storage, processing, bandwidth, and active user accounts).',
    status: 'active',
  },
  {
    seedId: 'cs-cloud-007',
    title: 'Infrastructure as a Service (IaaS)',
    domain: 'Computer Science',
    topics: ['Cloud Computing'],
    sourceType: 'Standard',
    sourceOrganization: 'ISO/IEC',
    sourceUrl: 'https://www.iso.org/standard/60544.html',
    description: 'Cloud delivery model supplying fundamental computing resources.',
    text: 'Infrastructure as a Service (IaaS) provides consumers with processing, storage, networks, and fundamental computing resources where the consumer can deploy and run arbitrary software, including operating systems and applications.',
    status: 'active',
  },
  {
    seedId: 'cs-cloud-008',
    title: 'Platform as a Service (PaaS)',
    domain: 'Computer Science',
    topics: ['Cloud Computing'],
    sourceType: 'Standard',
    sourceOrganization: 'ISO/IEC',
    sourceUrl: 'https://www.iso.org/standard/60544.html',
    description: 'Cloud delivery model providing application runtime environment.',
    text: 'Platform as a Service (PaaS) enables consumers to deploy onto the cloud infrastructure consumer-created or acquired applications created using programming languages, libraries, services, and tools supported by the provider.',
    status: 'active',
  },
  {
    seedId: 'cs-cloud-009',
    title: 'Software as a Service (SaaS)',
    domain: 'Computer Science',
    topics: ['Cloud Computing'],
    sourceType: 'Standard',
    sourceOrganization: 'ISO/IEC',
    sourceUrl: 'https://www.iso.org/standard/60544.html',
    description: 'Cloud delivery model providing application software over networks.',
    text: 'Software as a Service (SaaS) provides applications running on a cloud infrastructure accessible from various client devices through either a thin client interface, such as a web browser, or a program interface.',
    status: 'active',
  },
  {
    seedId: 'cs-cloud-010',
    title: 'Virtual Machine Hypervisors',
    domain: 'Computer Science',
    topics: ['Cloud Computing', 'Operating Systems'],
    sourceType: 'Technical Documentation',
    sourceOrganization: 'IEEE',
    sourceUrl: 'https://ieeexplore.ieee.org/document/4358217',
    description: 'Hypervisor virtualization abstraction in cloud hardware.',
    text: 'A hypervisor (or Virtual Machine Monitor) is software, firmware, or hardware that creates and runs virtual machines by isolating operating systems and resources from the underlying physical hardware.',
    status: 'active',
  },
  {
    seedId: 'cs-cloud-011',
    title: 'OS-Level Container Isolation',
    domain: 'Computer Science',
    topics: ['Cloud Computing', 'Operating Systems'],
    sourceType: 'Technical Documentation',
    sourceOrganization: 'Linux Kernel Documentation',
    sourceUrl: 'https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html',
    description: 'Container virtualization sharing host kernel resources.',
    text: 'Containers provide operating system-level virtualization where multiple isolated user-space instances share the single host operating system kernel, resulting in significantly lower resource overhead compared to hardware virtual machines.',
    status: 'active',
  },
  {
    seedId: 'cs-cloud-012',
    title: 'Public Cloud Deployment Model',
    domain: 'Computer Science',
    topics: ['Cloud Computing'],
    sourceType: 'Official Documentation',
    sourceOrganization: 'NIST',
    sourceUrl: 'https://csrc.nist.gov/publications/detail/sp/800-145/final',
    description: 'Multi-tenant cloud infrastructure open to general public.',
    text: 'A public cloud infrastructure is provisioned for open use by the general public. It may be owned, managed, and operated by a business, academic, or government organization, and exists on the premises of the cloud provider.',
    status: 'active',
  },
  {
    seedId: 'cs-cloud-013',
    title: 'Hybrid Cloud Architecture',
    domain: 'Computer Science',
    topics: ['Cloud Computing', 'Distributed Systems'],
    sourceType: 'Official Documentation',
    sourceOrganization: 'NIST',
    sourceUrl: 'https://csrc.nist.gov/publications/detail/sp/800-145/final',
    description: 'Interoperable composite cloud deployment model.',
    text: 'A hybrid cloud infrastructure is a composition of two or more distinct cloud infrastructures (private, community, or public) that remain unique entities but are bound together by standardized or proprietary technology enabling data and application portability.',
    status: 'active',
  },

  // =========================================================================
  // 2. DATABASE MANAGEMENT SYSTEMS (13 Entries)
  // =========================================================================
  {
    seedId: 'cs-dbms-001',
    title: 'Database Management System (DBMS) Definition',
    domain: 'Computer Science',
    topics: ['Database Management Systems'],
    sourceType: 'Academic Textbook',
    sourceOrganization: 'ACM',
    sourceUrl: 'https://dl.acm.org/doi/book/10.5555/128687',
    description: 'Software suite managing structured data storage and access.',
    text: 'A Database Management System (DBMS) is a software suite designed to define, manipulate, retrieve, and manage data in a database, ensuring data integrity, security, concurrency control, and automated backup management.',
    status: 'active',
  },
  {
    seedId: 'cs-dbms-002',
    title: 'Relational Database Model',
    domain: 'Computer Science',
    topics: ['Database Management Systems'],
    sourceType: 'Academic Textbook',
    sourceOrganization: 'ACM',
    sourceUrl: 'https://dl.acm.org/doi/10.1145/362384.362685',
    description: 'Codd relational model structuring data into tables and tuples.',
    text: 'The relational database model organizes data into two-dimensional tables (relations) consisting of rows (tuples) and columns (attributes), where data relationships are represented explicitly through matching key values.',
    status: 'active',
  },
  {
    seedId: 'cs-dbms-003',
    title: 'Primary Key Uniqueness Constraint',
    domain: 'Computer Science',
    topics: ['Database Management Systems'],
    sourceType: 'Technical Documentation',
    sourceOrganization: 'Oracle Documentation',
    sourceUrl: 'https://docs.oracle.com/en/database/oracle/oracle-database/',
    description: 'Primary key database constraint for row identification.',
    text: 'A primary key is a column or set of columns that uniquely identifies each row in a database table. Primary keys must contain unique values and cannot contain null values.',
    status: 'active',
  },
  {
    seedId: 'cs-dbms-004',
    title: 'Foreign Key Referential Integrity',
    domain: 'Computer Science',
    topics: ['Database Management Systems'],
    sourceType: 'Technical Documentation',
    sourceOrganization: 'Oracle Documentation',
    sourceUrl: 'https://docs.oracle.com/en/database/oracle/oracle-database/',
    description: 'Foreign key establishing relationships between tables.',
    text: 'A foreign key is a column or group of columns in one table that references the primary key of another table, enforcing referential integrity by preventing orphan rows.',
    status: 'active',
  },
  {
    seedId: 'cs-dbms-005',
    title: 'Structured Query Language (SQL)',
    domain: 'Computer Science',
    topics: ['Database Management Systems'],
    sourceType: 'Standard',
    sourceOrganization: 'ISO/IEC',
    sourceUrl: 'https://www.iso.org/standard/63555.html',
    description: 'Standardized query language for relational database operations.',
    text: 'Structured Query Language (SQL) is the ANSI/ISO standard domain-specific language used for managing relational databases through Data Definition Language (DDL) and Data Manipulation Language (DML) commands.',
    status: 'active',
  },
  {
    seedId: 'cs-dbms-006',
    title: 'ACID Property: Atomicity',
    domain: 'Computer Science',
    topics: ['Database Management Systems'],
    sourceType: 'Academic Textbook',
    sourceOrganization: 'ACM',
    sourceUrl: 'https://dl.acm.org/doi/10.1145/383059.383071',
    description: 'All-or-nothing execution of database transactions.',
    text: 'Atomicity guarantees that all operations within a database transaction are completed successfully, or none are executed. If any statement in the transaction fails, the transaction is aborted and rolled back entirely.',
    status: 'active',
  },
  {
    seedId: 'cs-dbms-007',
    title: 'ACID Property: Consistency',
    domain: 'Computer Science',
    topics: ['Database Management Systems'],
    sourceType: 'Academic Textbook',
    sourceOrganization: 'ACM',
    sourceUrl: 'https://dl.acm.org/doi/10.1145/383059.383071',
    description: 'Database state validation before and after transactions.',
    text: 'Consistency ensures that a transaction brings the database from one valid state to another, maintaining all predefined rules, unique constraints, primary keys, foreign keys, and triggers.',
    status: 'active',
  },
  {
    seedId: 'cs-dbms-008',
    title: 'ACID Property: Isolation',
    domain: 'Computer Science',
    topics: ['Database Management Systems'],
    sourceType: 'Academic Textbook',
    sourceOrganization: 'ACM',
    sourceUrl: 'https://dl.acm.org/doi/10.1145/383059.383071',
    description: 'Concurrent transaction isolation preventing data corruption.',
    text: 'Isolation ensures that concurrent execution of transactions leaves the database in the same state that would be obtained if transactions were executed sequentially, preventing dirty reads and phantom reads.',
    status: 'active',
  },
  {
    seedId: 'cs-dbms-009',
    title: 'ACID Property: Durability',
    domain: 'Computer Science',
    topics: ['Database Management Systems'],
    sourceType: 'Academic Textbook',
    sourceOrganization: 'ACM',
    sourceUrl: 'https://dl.acm.org/doi/10.1145/383059.383071',
    description: 'Persistent storage of committed transactions.',
    text: 'Durability guarantees that once a transaction has committed, its changes survive permanently in non-volatile storage, even in the event of system failures or power outages.',
    status: 'active',
  },
  {
    seedId: 'cs-dbms-010',
    title: 'First Normal Form (1NF)',
    domain: 'Computer Science',
    topics: ['Database Management Systems'],
    sourceType: 'Academic Textbook',
    sourceOrganization: 'ACM',
    sourceUrl: 'https://dl.acm.org/doi/10.1145/362384.362685',
    description: 'Database normalization rule eliminating repeating groups.',
    text: 'First Normal Form (1NF) requires that all columns in a relational table contain atomic (indivisible) values and that each entry in a column contains a single value of that domain, eliminating repeating groups.',
    status: 'active',
  },
  {
    seedId: 'cs-dbms-011',
    title: 'Second Normal Form (2NF)',
    domain: 'Computer Science',
    topics: ['Database Management Systems'],
    sourceType: 'Academic Textbook',
    sourceOrganization: 'ACM',
    sourceUrl: 'https://dl.acm.org/doi/10.1145/362384.362685',
    description: 'Normalization rule removing partial key dependencies.',
    text: 'Second Normal Form (2NF) requires that a table is in 1NF and that all non-key attributes are fully functionally dependent on the entire primary key, eliminating partial functional dependencies.',
    status: 'active',
  },
  {
    seedId: 'cs-dbms-012',
    title: 'Third Normal Form (3NF)',
    domain: 'Computer Science',
    topics: ['Database Management Systems'],
    sourceType: 'Academic Textbook',
    sourceOrganization: 'ACM',
    sourceUrl: 'https://dl.acm.org/doi/10.1145/362384.362685',
    description: 'Normalization rule removing transitive dependencies.',
    text: 'Third Normal Form (3NF) requires that a table is in 2NF and that no non-key attribute is transitively dependent on the primary key, meaning non-key attributes must depend solely on the candidate key.',
    status: 'active',
  },
  {
    seedId: 'cs-dbms-013',
    title: 'Database Indexing Optimization',
    domain: 'Computer Science',
    topics: ['Database Management Systems'],
    sourceType: 'Technical Documentation',
    sourceOrganization: 'Oracle Documentation',
    sourceUrl: 'https://docs.oracle.com/en/database/oracle/oracle-database/',
    description: 'Data structure indexing accelerating query retrieval.',
    text: 'A database index is a data structure (typically a B-Tree or Hash Table) that improves the speed of data retrieval operations on a database table at the cost of additional write overhead and storage space.',
    status: 'active',
  },

  // =========================================================================
  // 3. OPERATING SYSTEMS (13 Entries)
  // =========================================================================
  {
    seedId: 'cs-os-001',
    title: 'Operating System Definition and Role',
    domain: 'Computer Science',
    topics: ['Operating Systems'],
    sourceType: 'Academic Textbook',
    sourceOrganization: 'IEEE',
    sourceUrl: 'https://www.ieee.org/',
    description: 'System software managing hardware and application interfaces.',
    text: 'An Operating System (OS) is system software that acts as an intermediary between computer hardware and user applications, managing hardware resources (CPU, memory, storage, I/O devices) and providing common services for execution.',
    status: 'active',
  },
  {
    seedId: 'cs-os-002',
    title: 'Operating System Kernel',
    domain: 'Computer Science',
    topics: ['Operating Systems'],
    sourceType: 'Technical Documentation',
    sourceOrganization: 'Linux Kernel Documentation',
    sourceUrl: 'https://www.kernel.org/',
    description: 'Core component of operating system running in privileged mode.',
    text: 'The kernel is the core component of an operating system executing in supervisor mode. It directly controls hardware abstractions, process lifecycle, memory allocation, and hardware device interrupts.',
    status: 'active',
  },
  {
    seedId: 'cs-os-003',
    title: 'Process Execution State Model',
    domain: 'Computer Science',
    topics: ['Operating Systems'],
    sourceType: 'Academic Textbook',
    sourceOrganization: 'IEEE',
    sourceUrl: 'https://www.ieee.org/',
    description: 'Process definition and active execution lifecycle.',
    text: 'A process is an instance of a computer program in execution, containing program code, active memory (stack, heap, data), register state, and open file descriptors managed by a Process Control Block (PCB).',
    status: 'active',
  },
  {
    seedId: 'cs-os-004',
    title: 'Thread Execution Unit',
    domain: 'Computer Science',
    topics: ['Operating Systems'],
    sourceType: 'Academic Textbook',
    sourceOrganization: 'IEEE',
    sourceUrl: 'https://www.ieee.org/',
    description: 'Lightweight execution unit within a process space.',
    text: 'A thread is the smallest unit of CPU execution within a process. Multiple threads belonging to the same process share the process memory address space, heap, and file resources but maintain independent registers and stack.',
    status: 'active',
  },
  {
    seedId: 'cs-os-005',
    title: 'CPU Preemptive Scheduling',
    domain: 'Computer Science',
    topics: ['Operating Systems'],
    sourceType: 'Academic Textbook',
    sourceOrganization: 'IEEE',
    sourceUrl: 'https://www.ieee.org/',
    description: 'CPU scheduling algorithms allocating process runtime.',
    text: 'CPU scheduling allocates processor execution time among ready processes. Preemptive scheduling algorithms (e.g., Round Robin, Shortest Remaining Time First) interrupt active processes when higher-priority tasks enter the ready queue.',
    status: 'active',
  },
  {
    seedId: 'cs-os-006',
    title: 'Virtual Memory and Paging',
    domain: 'Computer Science',
    topics: ['Operating Systems'],
    sourceType: 'Academic Textbook',
    sourceOrganization: 'IEEE',
    sourceUrl: 'https://www.ieee.org/',
    description: 'Virtual memory address translation and fixed-size paging.',
    text: 'Virtual memory creates an abstraction of large sequential memory by mapping process virtual addresses to physical RAM frames using fixed-size blocks called pages, managed by the Memory Management Unit (MMU).',
    status: 'active',
  },
  {
    seedId: 'cs-os-007',
    title: 'Page Fault Handling',
    domain: 'Computer Science',
    topics: ['Operating Systems'],
    sourceType: 'Academic Textbook',
    sourceOrganization: 'IEEE',
    sourceUrl: 'https://www.ieee.org/',
    description: 'Hardware interrupt triggering page load from disk.',
    text: 'A page fault is an exception raised by memory management hardware when a process accesses a virtual memory page that is not currently mapped into physical RAM, requiring the OS kernel to load the page from secondary storage.',
    status: 'active',
  },
  {
    seedId: 'cs-os-008',
    title: 'Deadlock Necessary Conditions',
    domain: 'Computer Science',
    topics: ['Operating Systems'],
    sourceType: 'Academic Textbook',
    sourceOrganization: 'IEEE',
    sourceUrl: 'https://www.ieee.org/',
    description: 'Coffman conditions required for system deadlock.',
    text: 'A deadlock occurs when a set of processes are blocked because each holds a resource while waiting for another. Deadlocks require four Coffman conditions simultaneously: Mutual Exclusion, Hold and Wait, No Preemption, and Circular Wait.',
    status: 'active',
  },
  {
    seedId: 'cs-os-009',
    title: 'Semaphore Synchronization Construct',
    domain: 'Computer Science',
    topics: ['Operating Systems'],
    sourceType: 'Academic Textbook',
    sourceOrganization: 'IEEE',
    sourceUrl: 'https://www.ieee.org/',
    description: 'Dijkstra semaphore variable controlling resource concurrency.',
    text: 'A semaphore is a protected integer variable introduced by Dijkstra used for process synchronization and concurrency control through atomic Wait (P) and Signal (V) operations.',
    status: 'active',
  },
  {
    seedId: 'cs-os-010',
    title: 'Mutex Locking Mechanism',
    domain: 'Computer Science',
    topics: ['Operating Systems'],
    sourceType: 'Academic Textbook',
    sourceOrganization: 'IEEE',
    sourceUrl: 'https://www.ieee.org/',
    description: 'Mutual exclusion lock preventing race conditions.',
    text: 'A Mutex (Mutual Exclusion lock) is a synchronization primitive owned by a single thread at a time, used to protect critical sections of code and prevent data corruption caused by concurrent memory writes.',
    status: 'active',
  },
  {
    seedId: 'cs-os-011',
    title: 'Context Switching Overhead',
    domain: 'Computer Science',
    topics: ['Operating Systems'],
    sourceType: 'Technical Documentation',
    sourceOrganization: 'Linux Kernel Documentation',
    sourceUrl: 'https://www.kernel.org/',
    description: 'CPU state saving and loading during process transitions.',
    text: 'Context switching is the process of saving the current execution state (registers, stack pointer, page table reference) of an active process or thread and restoring the saved state of another process to resume execution.',
    status: 'active',
  },
  {
    seedId: 'cs-os-012',
    title: 'System Call Kernel Interface',
    domain: 'Computer Science',
    topics: ['Operating Systems'],
    sourceType: 'Technical Documentation',
    sourceOrganization: 'POSIX Standard',
    sourceUrl: 'https://pubs.opengroup.org/onlinepubs/9699919799/',
    description: 'Programmatic boundary between user space and kernel mode.',
    text: 'A system call is a programmatic interface through which user-space application programs request privileged services (file I/O, process creation, network sockets) directly from the operating system kernel.',
    status: 'active',
  },
  {
    seedId: 'cs-os-013',
    title: 'File System Directory Tree Abstraction',
    domain: 'Computer Science',
    topics: ['Operating Systems'],
    sourceType: 'Technical Documentation',
    sourceOrganization: 'POSIX Standard',
    sourceUrl: 'https://pubs.opengroup.org/onlinepubs/9699919799/',
    description: 'Hierarchical file storage organizing non-volatile data.',
    text: 'A file system provides a logical hierarchical directory structure for storing, organizing, retrieving, and protecting files on physical storage devices, maintaining metadata through data structures such as index nodes (inodes).',
    status: 'active',
  },

  // =========================================================================
  // 4. COMPUTER NETWORKS (13 Entries)
  // =========================================================================
  {
    seedId: 'cs-net-001',
    title: 'OSI 7-Layer Reference Model',
    domain: 'Computer Science',
    topics: ['Computer Networks'],
    sourceType: 'Standard',
    sourceOrganization: 'ISO/IEC',
    sourceUrl: 'https://www.iso.org/standard/26885.html',
    description: 'Standardized 7-layer networking architecture framework.',
    text: 'The Open Systems Interconnection (OSI) model standardizes network communication into seven distinct layers: Physical, Data Link, Network, Transport, Session, Presentation, and Application layers.',
    status: 'active',
  },
  {
    seedId: 'cs-net-002',
    title: 'Transmission Control Protocol (TCP)',
    domain: 'Computer Science',
    topics: ['Computer Networks'],
    sourceType: 'Official Documentation',
    sourceOrganization: 'RFC Editor',
    sourceUrl: 'https://www.rfc-editor.org/rfc/rfc9293.html',
    description: 'Reliable connection-oriented transport layer protocol.',
    text: 'Transmission Control Protocol (TCP) is a connection-oriented, reliable transport protocol that guarantees ordered, error-checked delivery of a stream of octets between applications over an IP network via a three-way handshake.',
    status: 'active',
  },
  {
    seedId: 'cs-net-003',
    title: 'User Datagram Protocol (UDP)',
    domain: 'Computer Science',
    topics: ['Computer Networks'],
    sourceType: 'Official Documentation',
    sourceOrganization: 'RFC Editor',
    sourceUrl: 'https://www.rfc-editor.org/rfc/rfc768.html',
    description: 'Low-latency connectionless transport layer protocol.',
    text: 'User Datagram Protocol (UDP) is a connectionless transport protocol offering lightweight, low-latency transmission without establishing connection handshakes, packet acknowledgment, flow control, or message ordering.',
    status: 'active',
  },
  {
    seedId: 'cs-net-004',
    title: 'Internet Protocol (IP) Addressing',
    domain: 'Computer Science',
    topics: ['Computer Networks'],
    sourceType: 'Official Documentation',
    sourceOrganization: 'RFC Editor',
    sourceUrl: 'https://www.rfc-editor.org/rfc/rfc791.html',
    description: 'Network layer protocol providing IP addressing and routing.',
    text: 'The Internet Protocol (IP) operates at the network layer to provide logical addressing (IPv4/IPv6) and packet routing across network boundaries on a best-effort delivery basis.',
    status: 'active',
  },
  {
    seedId: 'cs-net-005',
    title: 'Domain Name System (DNS) Resolution',
    domain: 'Computer Science',
    topics: ['Computer Networks', 'Web Technologies'],
    sourceType: 'Official Documentation',
    sourceOrganization: 'RFC Editor',
    sourceUrl: 'https://www.rfc-editor.org/rfc/rfc1035.html',
    description: 'Hierarchical name resolution translating domains to IP addresses.',
    text: 'The Domain Name System (DNS) is a distributed hierarchical naming database that translates human-readable domain names (e.g., trustlens.org) into numerical IP addresses required for network routing.',
    status: 'active',
  },
  {
    seedId: 'cs-net-006',
    title: 'Router Packet Forwarding',
    domain: 'Computer Science',
    topics: ['Computer Networks'],
    sourceType: 'Technical Documentation',
    sourceOrganization: 'IEEE',
    sourceUrl: 'https://www.ieee.org/',
    description: 'Layer 3 network device routing packets between subnets.',
    text: 'A router is a Layer 3 network hardware device that inspects destination IP addresses in incoming packets and consults routing tables to forward packets across interconnected networks.',
    status: 'active',
  },
  {
    seedId: 'cs-net-007',
    title: 'Address Resolution Protocol (ARP)',
    domain: 'Computer Science',
    topics: ['Computer Networks'],
    sourceType: 'Official Documentation',
    sourceOrganization: 'RFC Editor',
    sourceUrl: 'https://www.rfc-editor.org/rfc/rfc826.html',
    description: 'Protocol mapping IP addresses to physical MAC addresses.',
    text: 'Address Resolution Protocol (ARP) translates 32-bit IPv4 network layer addresses into 48-bit physical Media Access Control (MAC) addresses within a local Ethernet network segment.',
    status: 'active',
  },
  {
    seedId: 'cs-net-008',
    title: 'Hypertext Transfer Protocol (HTTP)',
    domain: 'Computer Science',
    topics: ['Computer Networks', 'Web Technologies'],
    sourceType: 'Official Documentation',
    sourceOrganization: 'W3C / IETF',
    sourceUrl: 'https://www.rfc-editor.org/rfc/rfc9110.html',
    description: 'Application layer protocol for distributed web media.',
    text: 'Hypertext Transfer Protocol (HTTP) is an application-layer request-response protocol used for transmitting hypermedia documents across the World Wide Web over TCP port 80.',
    status: 'active',
  },
  {
    seedId: 'cs-net-009',
    title: 'HTTPS Encryption via TLS/SSL',
    domain: 'Computer Science',
    topics: ['Computer Networks', 'Cybersecurity'],
    sourceType: 'Official Documentation',
    sourceOrganization: 'IETF',
    sourceUrl: 'https://www.rfc-editor.org/rfc/rfc8446.html',
    description: 'Secure HTTP communication protocol encrypted with TLS.',
    text: 'HTTPS (HTTP Secure) encrypts HTTP web communication using Transport Layer Security (TLS) or SSL to provide confidentiality, authentication, and data integrity over TCP port 443.',
    status: 'active',
  },
  {
    seedId: 'cs-net-010',
    title: 'Network Subnetting and CIDR',
    domain: 'Computer Science',
    topics: ['Computer Networks'],
    sourceType: 'Official Documentation',
    sourceOrganization: 'RFC Editor',
    sourceUrl: 'https://www.rfc-editor.org/rfc/rfc4632.html',
    description: 'Subnet masking and Classless Inter-Domain Routing.',
    text: 'Subnetting divides a single IP network into smaller sub-networks using subnet masks. Classless Inter-Domain Routing (CIDR) optimizes IP allocation by specifying variable-length prefix masks.',
    status: 'active',
  },
  {
    seedId: 'cs-net-011',
    title: 'Network Switch (Layer 2)',
    domain: 'Computer Science',
    topics: ['Computer Networks'],
    sourceType: 'Technical Documentation',
    sourceOrganization: 'IEEE',
    sourceUrl: 'https://www.ieee.org/',
    description: 'Data link layer device switching frames via MAC address tables.',
    text: 'A network switch operates at Layer 2 (Data Link Layer) of the OSI model, forwarding Ethernet frames between connected local devices based on physical MAC address lookup tables.',
    status: 'active',
  },
  {
    seedId: 'cs-net-012',
    title: 'Firewall Access Control Security',
    domain: 'Computer Science',
    topics: ['Computer Networks', 'Cybersecurity'],
    sourceType: 'Technical Documentation',
    sourceOrganization: 'NIST',
    sourceUrl: 'https://csrc.nist.gov/publications/detail/sp/800-41/rev-1/final',
    description: 'Packet filtering security system inspecting network traffic.',
    text: 'A firewall is a network security system that monitors and filters incoming and outgoing network traffic based on predefined security rules, preventing unauthorized access between networks.',
    status: 'active',
  },
  {
    seedId: 'cs-net-013',
    title: 'Connection-Oriented vs Connectionless Communication',
    domain: 'Computer Science',
    topics: ['Computer Networks'],
    sourceType: 'Academic Textbook',
    sourceOrganization: 'IEEE',
    sourceUrl: 'https://www.ieee.org/',
    description: 'Comparison of transport protocol connection paradigms.',
    text: 'Connection-oriented communication (e.g., TCP) establishes a logical session connection before transferring data, guaranteeing delivery order. Connectionless communication (e.g., UDP) transmits independent packets without prior session setup.',
    status: 'active',
  },

  // =========================================================================
  // 5. DATA STRUCTURES AND ALGORITHMS (13 Entries)
  // =========================================================================
  {
    seedId: 'cs-dsa-001',
    title: 'Array Data Structure',
    domain: 'Computer Science',
    topics: ['Data Structures and Algorithms'],
    sourceType: 'Educational Resource',
    sourceOrganization: 'MIT OpenCourseWare',
    sourceUrl: 'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/',
    description: 'Contiguous memory array with constant time random access.',
    text: 'An array is a fundamental data structure consisting of a collection of elements of the same type stored in contiguous memory locations, allowing O(1) constant-time direct indexing access by position.',
    status: 'active',
  },
  {
    seedId: 'cs-dsa-002',
    title: 'Singly Linked List Data Structure',
    domain: 'Computer Science',
    topics: ['Data Structures and Algorithms'],
    sourceType: 'Educational Resource',
    sourceOrganization: 'MIT OpenCourseWare',
    sourceUrl: 'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/',
    description: 'Linear node sequence linked by next pointer references.',
    text: 'A singly linked list is a linear data structure composed of nodes, where each node stores data and a pointer reference to the next node in the sequence, allowing O(1) dynamic node insertions.',
    status: 'active',
  },
  {
    seedId: 'cs-dsa-003',
    title: 'Doubly Linked List',
    domain: 'Computer Science',
    topics: ['Data Structures and Algorithms'],
    sourceType: 'Educational Resource',
    sourceOrganization: 'MIT OpenCourseWare',
    sourceUrl: 'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/',
    description: 'Bidirectional linked list with prev and next pointers.',
    text: 'A doubly linked list is a linked data structure where each node contains pointers to both its successor (next) and predecessor (previous) nodes, enabling bidirectional traversal.',
    status: 'active',
  },
  {
    seedId: 'cs-dsa-004',
    title: 'Stack LIFO Data Structure',
    domain: 'Computer Science',
    topics: ['Data Structures and Algorithms'],
    sourceType: 'Educational Resource',
    sourceOrganization: 'MIT OpenCourseWare',
    sourceUrl: 'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/',
    description: 'Last-In First-Out linear stack structure.',
    text: 'A stack is an abstract linear data structure operating on the Last-In, First-Out (LIFO) principle, supporting push (insertion) and pop (deletion) operations performed exclusively at the top of the stack.',
    status: 'active',
  },
  {
    seedId: 'cs-dsa-005',
    title: 'Queue FIFO Data Structure',
    domain: 'Computer Science',
    topics: ['Data Structures and Algorithms'],
    sourceType: 'Educational Resource',
    sourceOrganization: 'MIT OpenCourseWare',
    sourceUrl: 'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/',
    description: 'First-In First-Out linear queue structure.',
    text: 'A queue is a linear data structure operating on the First-In, First-Out (FIFO) principle, where elements are enqueued at the rear and dequeued from the front in arrival order.',
    status: 'active',
  },
  {
    seedId: 'cs-dsa-006',
    title: 'Binary Search Tree (BST)',
    domain: 'Computer Science',
    topics: ['Data Structures and Algorithms'],
    sourceType: 'Educational Resource',
    sourceOrganization: 'MIT OpenCourseWare',
    sourceUrl: 'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/',
    description: 'Sorted binary tree structure where left subtrees contain smaller elements.',
    text: 'A Binary Search Tree (BST) is a hierarchical node-based tree structure where every node satisfies the property that all values in its left subtree are smaller than its key, and all values in its right subtree are greater.',
    status: 'active',
  },
  {
    seedId: 'cs-dsa-007',
    title: 'Graph Adjacency Representation',
    domain: 'Computer Science',
    topics: ['Data Structures and Algorithms'],
    sourceType: 'Educational Resource',
    sourceOrganization: 'MIT OpenCourseWare',
    sourceUrl: 'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/',
    description: 'Non-linear graph composed of vertices and edges.',
    text: 'A graph is a non-linear data structure consisting of a set of vertices (nodes) connected by edges (relationships), commonly represented using Adjacency Lists or Adjacency Matrices.',
    status: 'active',
  },
  {
    seedId: 'cs-dsa-008',
    title: 'Big O Complexity Analysis',
    domain: 'Computer Science',
    topics: ['Data Structures and Algorithms'],
    sourceType: 'Educational Resource',
    sourceOrganization: 'MIT OpenCourseWare',
    sourceUrl: 'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/',
    description: 'Asymptotic notation analyzing algorithm time and space growth.',
    text: 'Big O notation characterizes the upper bound of an algorithm time or space complexity as input size N grows toward infinity, providing standardized performance measurement (e.g., O(1), O(log N), O(N), O(N log N)).',
    status: 'active',
  },
  {
    seedId: 'cs-dsa-009',
    title: 'Binary Search Algorithm',
    domain: 'Computer Science',
    topics: ['Data Structures and Algorithms'],
    sourceType: 'Educational Resource',
    sourceOrganization: 'MIT OpenCourseWare',
    sourceUrl: 'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/',
    description: 'Logarithmic search algorithm for ordered arrays.',
    text: 'Binary search is an efficient search algorithm operating on sorted arrays that repeatedly divides the search interval in half, achieving logarithmic O(log N) time complexity.',
    status: 'active',
  },
  {
    seedId: 'cs-dsa-010',
    title: 'Quick Sort Algorithm',
    domain: 'Computer Science',
    topics: ['Data Structures and Algorithms'],
    sourceType: 'Educational Resource',
    sourceOrganization: 'MIT OpenCourseWare',
    sourceUrl: 'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/',
    description: 'Divide-and-conquer sorting algorithm partitioning elements around pivot.',
    text: 'Quick sort is an efficient divide-and-conquer sorting algorithm that selects a pivot element, partitions the array such that smaller elements precede the pivot, and recursively sorts sub-arrays in average O(N log N) time.',
    status: 'active',
  },
  {
    seedId: 'cs-dsa-011',
    title: 'Merge Sort Algorithm',
    domain: 'Computer Science',
    topics: ['Data Structures and Algorithms'],
    sourceType: 'Educational Resource',
    sourceOrganization: 'MIT OpenCourseWare',
    sourceUrl: 'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/',
    description: 'Stable divide-and-conquer sorting algorithm with worst-case O(N log N) bound.',
    text: 'Merge sort is a stable divide-and-conquer sorting algorithm that recursively splits an array into halves, sorts each half, and merges the sorted halves back together in guaranteed O(N log N) worst-case time.',
    status: 'active',
  },
  {
    seedId: 'cs-dsa-012',
    title: 'Hash Table Collision Resolution',
    domain: 'Computer Science',
    topics: ['Data Structures and Algorithms'],
    sourceType: 'Educational Resource',
    sourceOrganization: 'MIT OpenCourseWare',
    sourceUrl: 'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/',
    description: 'Hash mapping structure with chaining and open addressing.',
    text: 'A hash table maps key-value pairs into array buckets using a hash function. Collisions (where two keys hash to the same bucket) are resolved using Separate Chaining (linked lists) or Open Addressing (linear/quadratic probing).',
    status: 'active',
  },
  {
    seedId: 'cs-dsa-013',
    title: 'Recursion Base Case Principle',
    domain: 'Computer Science',
    topics: ['Data Structures and Algorithms'],
    sourceType: 'Educational Resource',
    sourceOrganization: 'MIT OpenCourseWare',
    sourceUrl: 'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/',
    description: 'Algorithmic self-referential technique requiring terminating base condition.',
    text: 'Recursion is a method where a function solves a problem by calling smaller instances of itself. Every recursive algorithm must include a base case condition that terminates recursion without further self-calls, avoiding infinite call stack overflow.',
    status: 'active',
  },
];

module.exports = {
  TRUSTED_KNOWLEDGE_SEED,
};
