/**
 * Centralized Activity Log Action Types and Categories
 */

const ACTIVITY_ACTIONS = {
  USER_REGISTERED: 'USER_REGISTERED',
  USER_ACTIVATED: 'USER_ACTIVATED',
  USER_SUSPENDED: 'USER_SUSPENDED',
  REPORT_CREATED: 'REPORT_CREATED',
  REPORT_ANALYSIS_STARTED: 'REPORT_ANALYSIS_STARTED',
  REPORT_ANALYSIS_COMPLETED: 'REPORT_ANALYSIS_COMPLETED',
  REPORT_ANALYSIS_FAILED: 'REPORT_ANALYSIS_FAILED',
  KNOWLEDGE_SOURCE_CREATED: 'KNOWLEDGE_SOURCE_CREATED',
  KNOWLEDGE_SOURCE_ACTIVATED: 'KNOWLEDGE_SOURCE_ACTIVATED',
  KNOWLEDGE_SOURCE_DEACTIVATED: 'KNOWLEDGE_SOURCE_DEACTIVATED',
  KNOWLEDGE_SOURCE_DELETED: 'KNOWLEDGE_SOURCE_DELETED',
};

const ACTIVITY_CATEGORIES = {
  USER: 'USER',
  REPORT: 'REPORT',
  KNOWLEDGE_SOURCE: 'KNOWLEDGE_SOURCE',
  SYSTEM: 'SYSTEM',
};

module.exports = {
  ACTIVITY_ACTIONS,
  ACTIVITY_CATEGORIES,
};
